// Code generated by MockGen. DO NOT EDIT.
// Source: flat_gateway.go

// Package flattener is a generated GoMock package.
package flattener

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGateway is a mock of Gateway interface.
type MockGateway struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayMockRecorder
}

// MockGatewayMockRecorder is the mock recorder for MockGateway.
type MockGatewayMockRecorder struct {
	mock *MockGateway
}

// NewMockGateway creates a new mock instance.
func NewMockGateway(ctrl *gomock.Controller) *MockGateway {
	mock := &MockGateway{ctrl: ctrl}
	mock.recorder = &MockGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGateway) EXPECT() *MockGatewayMockRecorder {
	return m.recorder
}

// FlatResponse mocks base method.
func (m *MockGateway) FlatResponse(arg0 []interface{}) FlatResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlatResponse", arg0)
	ret0, _ := ret[0].(FlatResponse)
	return ret0
}

// FlatResponse indicates an expected call of FlatResponse.
func (mr *MockGatewayMockRecorder) FlatResponse(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlatResponse", reflect.TypeOf((*MockGateway)(nil).FlatResponse), arg0)
}
